-- ============================================================================
--  MIGRACIÓN 20 — Carga catálogo definitivo: 30 normas (Matriz Legislativa)
--  Reemplazo total. severidad←Impacto, prob_fisc←Probabilidad (ISO equipo),
--  pesos←nivel de riesgo, materialidad←tema. Multas NULL, equipo ajusta en base.
-- ============================================================================

delete from respuestas;
delete from evaluaciones;
delete from norma_sector;
delete from normas;

insert into normas (clave, titulo, descripcion, categoria, tema, severidad, prob_fiscalizacion,
  tendencia, es_descalificante, peso_crediticio, peso_reputacional, fuente, jurisdiccion_id, vigente)
values
  ('CPEUM','Constitución Política de los Estado Unidos Méxicanos','Norma suprema que reconoce derechos humanos, ambiente sano, agua, propiedad de la Nación, rectoría económica y bases de responsabilidades.','jurisdiccional_documental','permisos_licencias',5,2,1.0,false,1.4,1.3,'https://www.diputados.gob.mx/LeyesBiblio/pdf/CPEUM.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('LGEEPA','Ley General del Equilibrio Ecológico y la Protección al Ambiente','Ley marco ambiental: política ecológica, evaluación de impacto ambiental, prevención y control de contaminación, áreas naturales protegidas e inspección.','ambiental','biodiversidad',4,4,1.0,false,1.4,1.3,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LGEEPA.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('LFD','Ley Federal de Derechos','Establece cuotas por servicios públicos y por uso o aprovechamiento de bienes del dominio público, incluyendo agua, zona federal, puertos y ambiente.','jurisdiccional_documental','permisos_licencias',3,3,1.0,false,0.6,0.5,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LFD.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('LAN','Ley de Aguas Nacionales','Regula aguas nacionales, concesiones, extracción, descargas, zonas federales, medición, pagos y preservación de calidad.','ambiental','agua',5,4,1.0,true,1.4,1.3,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LAN.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('CPF','Código Penal Federal','Tipifica delitos federales, incluidos ambientales, corrupción, operaciones con recursos de procedencia ilícita y otros relevantes al compliance.','jurisdiccional_documental','permisos_licencias',5,2,1.0,false,1.4,1.3,'https://www.diputados.gob.mx/LeyesBiblio/pdf/CPF.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('LGPGIR','Ley General para la Prevención y Gestión Integral de Residuos','Regula prevención, clasificación, manejo integral y responsabilidad por residuos peligrosos, mineros/metalúrgicos y de manejo especial.','ambiental','residuos',4,4,1.0,false,1.4,1.3,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LGPGIR.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('LAGR','Ley Agraria','Regula propiedad ejidal y comunal, asambleas, parcelamiento, transmisión, ocupación y sociedades rurales.','jurisdiccional_documental','permisos_licencias',4,3,1.0,false,1.0,0.9,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LAgra.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('LGCC','Ley General de Cambio Climático','Establece política nacional de mitigación/adaptación, inventarios, instrumentos económicos, transparencia y coordinación.','ambiental','cambio_climatico',3,3,1.0,false,0.6,0.5,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LGCC.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('LFSA','Ley Federal de Sanidad Animal','Protege sanidad y bienestar animal e inocuidad; regula movilización, establecimientos, trazabilidad y emergencias zoosanitarias.','ambiental','biodiversidad',5,4,1.0,true,1.4,1.3,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LFSA.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('LFRA','Ley Federal de Responsabilidad Ambiental','Regula responsabilidad, reparación y compensación por daño ambiental mediante acción judicial y mecanismos alternativos.','ambiental','biodiversidad',4,3,1.0,false,1.0,0.9,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LFRA.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('LDRS','Ley de Desarrollo Rural Sustentable','Marco para desarrollo rural, productividad, sustentabilidad, apoyos, organización y seguridad alimentaria.','jurisdiccional_documental','biodiversidad',3,3,1.0,false,0.6,0.5,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LDRS.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('PARIS','Acuerdo de París','Tratado climático vinculante para Estados: limita calentamiento, fortalece adaptación y alinea flujos financieros con bajas emisiones y resiliencia.','ambiental','cambio_climatico',3,2,1.0,false,0.6,0.5,'https://unfccc.int/files/meetings/paris_nov_2015/application/pdf/paris_agreement_spanish_.pdf',(select id from jurisdicciones where clave='INT'),true),
  ('CADH','Convención Americana sobre Derechos Humanos','Tratado regional que obliga al Estado a respetar y garantizar derechos y ofrecer protección judicial efectiva.','social','derechos_laborales',4,2,1.0,false,1.0,0.9,'https://www.oas.org/dil/esp/1969_Convenci%C3%B3n_Americana_sobre_Derechos_Humanos.pdf',(select id from jurisdicciones where clave='INT'),true),
  ('OIT','Organización Internacional del Trabajo','Conjunto de convenios, protocolos y recomendaciones sobre trabajo decente, libertad sindical, no discriminación, trabajo forzoso/infantil y SST.','social','derechos_laborales',4,3,1.0,false,1.0,0.9,'https://www.ilo.org/es/normas-internacionales-del-trabajo/convenios-protocolos-y-recomendaciones',(select id from jurisdicciones where clave='INT'),true),
  ('KMGBF','Marco de Biodiversidad de Kumming-Montreal','Marco global adoptado bajo el Convenio sobre Diversidad Biológica con 4 objetivos a 2050 y 23 metas a 2030.','ambiental','permisos_licencias',3,2,1.0,false,0.6,0.5,'https://www.cbd.int/doc/decisions/cop-15/cop-15-dec-04-es.pdf',(select id from jurisdicciones where clave='INT'),true),
  ('BEIJING','Plataforma de Beijing','Agenda internacional de 1995 con 12 esferas para igualdad, participación, economía, educación, salud y eliminación de violencia/discriminación.','social','derechos_laborales',2,1,1.0,false,0.3,0.3,'https://www.unwomen.org/es/digital-library/publications/2015/01/beijing-declaration',(select id from jurisdicciones where clave='INT'),true),
  ('LGDFS','Ley General de Desarrollo Forestal Sustentable','Marco normativo que regula la conservación, protección, restauración, producción y ordenación de los ecosistemas forestales de México.','ambiental','biodiversidad',5,4,1.0,true,1.4,1.3,'https://www.gob.mx/profepa/documentos/ley-general-de-desarrollo-forestal-sustentable',(select id from jurisdicciones where clave='FED'),true),
  ('LGAH','Ley General de Asentamientos Humanos, Ordenamiento Territorial y Desarrollo Urbano','Ordenamiento rector de la planeación y zonificación del territorio nacional y el desarrollo de centros de población.','jurisdiccional_documental','permisos_licencias',4,3,1.0,false,1.0,0.9,'https://www.gob.mx/sedatu/documentos/ley-general-de-asentamientos-humanos-ordenamiento-territorial-y-desarrollo-urbano',(select id from jurisdicciones where clave='FED'),true),
  ('LGEC','Ley General de Economía Circular','Promueve la reducción del desperdicio, la eficiencia en el uso de materiales y el reaprovechamiento de subproductos en las cadenas de valor.','ambiental','economia_circular',3,3,1.0,false,0.6,0.5,'https://www.diputados.gob.mx/LeyesBiblio/ref/lgec.htm',(select id from jurisdicciones where clave='FED'),true),
  ('LGSM','Ley General de Sociedades Mercantiles','Regula la constitución, funcionamiento, responsabilidad corporativa y disolución de las sociedades comerciales en México.','jurisdiccional_documental','permisos_licencias',4,3,1.0,false,1.0,0.9,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LGSM.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('ECUADOR','Principios de Ecuador','Marco voluntario de gestión del riesgo socioambiental adoptado por instituciones financieras internacionales para financiar proyectos de infraestructura y agroindustria.','social','derechos_laborales',4,2,1.0,false,1.0,0.9,'https://www.hsbc.com/who-we-are/esg-and-responsible-business/managing-risk/sustainability-risk/equator-principles',(select id from jurisdicciones where clave='INT'),true),
  ('LGA','Ley General de Aguas','Rige la explotación, uso, aprovechamiento, distribución y control del agua nacional y las descargas de aguas residuales.','ambiental','agua',5,4,1.0,false,1.4,1.3,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LGAg.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('KIOTO','Protocolo de Kioto','Tratado internacional vinculado a la CMNUCC que establece metas vinculantes de reducción de gases de efecto invernadero para los países firmantes.','ambiental','cambio_climatico',2,1,1.0,false,0.3,0.3,'https://unfccc.int/es/kyoto_protocol',(select id from jurisdicciones where clave='INT'),true),
  ('NOM127','NOM - 127 - SSA 1- 2021','Tiene como finalidad establecer los límites permisibles de calidad que debe cumplir el agua destinada al consumo humano, asegurando que los sistemas de abastecimiento públicos y privados entreguen agua segura y apta para consumo y es de observancia obligatoria en todo el territorio nacional.','ambiental','agua',4,3,1.0,false,1.0,0.9,'https://dof.gob.mx/nota_detalle_popup.php?codigo=5650705',(select id from jurisdicciones where clave='FED'),true),
  ('LMV','Ley del Mercado de Valores','es la legislación mexicana que regula la oferta, colocación, intermediación y negociación de valores en el mercado financiero. La ley establece las obligaciones de las sociedades emisoras, casas de bolsa, bolsas de valores, fondos de inversión y demás participantes del mercado, además de otorgar facultades de supervisión y vigilancia a la Comisión Nacional Bancaria y de Valores','jurisdiccional_documental','permisos_licencias',4,2,1.0,false,1.0,0.9,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LMV.pdf',(select id from jurisdicciones where clave='FED'),true),
  ('ISO14001','ISO 14001','Norma internacional que establece los requisitos para implementar un Sistema de Gestión Ambiental (SGA). Su objetivo es ayudar a las organizaciones a identificar, controlar y reducir sus impactos ambientales, cumplir la legislación aplicable y mejorar continuamente su desempeño ambiental.','ambiental','residuos',3,2,1.0,false,0.6,0.5,'https://www.iso.org/obp/ui#iso:std:iso:14001:ed-3:v1:es',(select id from jurisdicciones where clave='INT'),true),
  ('NOM001','NOM - 001 - SEMARNAT - 2021','Tiene como finalidad preservar los derechos humanos al agua y al saneamiento, garantizando la disponibilidad, accesibilidad, asequibilidad, calidad y seguridad del recurso hídrico, así como la protección de los ecosistemas acuáticos del país. Asimismo, Aplica será de observancia obligatoria para los responsables de las descargas de aguas residuales en cualquier tipo de cuerpo receptor propiedad de','ambiental','agua',4,4,1.0,false,1.4,1.3,'DOF - Diario Oficial de la Federación',(select id from jurisdicciones where clave='FED'),true),
  ('NOM015','NOM  - 015 - SEMARNAT/AGRICULTURA - 2023','Esta NOM establece las especificaciones técnicas para el uso del fuego en terrenos, temporalmente forestales, preferentemente forestales y de uso agropecuario, con el objetivo de prevenir y reducir incendios forestales y minimizar los impactos ambientales asociados a las quemas agrícolas y pecuarias.','ambiental','biodiversidad',4,4,1.0,true,1.4,1.3,'https://dof.gob.mx/nota_detalle_popup.php?codigo=5710189',(select id from jurisdicciones where clave='FED'),true),
  ('NOM052','NOM - 052 - SEMARNAT - 2005','Esta NOM establece las características, el procedimiento de identificación, la clasificación  y los listados oficiales para determinar si un residuo se considera peligroso. Evalúa propiedades de corrosividad, reactividad, explosivida, toxicidad ambiental, inflamabilidad y biológico-infecciiosa, con el fin de evitar riesgos al ambiente y salud','ambiental','residuos',4,4,1.0,false,1.4,1.3,'https://dof.gob.mx/normasOficiales/1055/SEMARNA/SEMARNA.htm',(select id from jurisdicciones where clave='FED'),true),
  ('LFT','Ley Federal  del Trabajo','La ley regula las relaciones entre trabajadores y empleadores en México, estableciendo derechos y obligaciones en materia de contratación, salarios, jornadas laborales, prestaciones, capacitación, seguridad y salud en el trabajo, así como mecanismos de protección de los derechos laborales.','social','derechos_laborales',4,4,1.0,true,1.4,1.3,'https://www.diputados.gob.mx/LeyesBiblio/pdf/LFT.pdf',(select id from jurisdicciones where clave='FED'),true);

-- norma_sector con materialidad EXPLÍCITA por clave (sin case, a prueba de fallos).
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='CPEUM';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='LGEEPA';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='LFD';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 5 from normas where clave='LAN';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='CPF';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='LGPGIR';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='LAGR';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='LGCC';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='LFSA';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='LFRA';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='LDRS';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='PARIS';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='CADH';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='OIT';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='KMGBF';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='BEIJING';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='LGDFS';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='LGAH';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='LGEC';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='LGSM';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='ECUADOR';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 5 from normas where clave='LGA';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='KIOTO';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 5 from normas where clave='NOM127';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='LMV';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='ISO14001';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 5 from normas where clave='NOM001';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='NOM015';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 2 from normas where clave='NOM052';
insert into norma_sector (norma_id, sector_id, aplica, materialidad) select id, '11111111-1111-1111-1111-111111111111', true, 4 from normas where clave='LFT';